customer:
    path:     /
    defaults: { _controller: "MondoBookingBundle:Customer:new" }

customer_show:
    path:     /{vernr}/show
    defaults: { _controller: "MondoBookingBundle:Customer:show" }

customer_new:
    path:     /new
    defaults: { _controller: "MondoBookingBundle:Customer:new" }

customer_create:
    path:     /create
    defaults: { _controller: "MondoBookingBundle:Customer:create" }
    requirements: { _method: post }

customer_verify:
    path:     /{vernr}/verify
    defaults: { _controller: "MondoBookingBundle:Customer:verify" }
